### ISSUE TITLE
How to convert the result to Gray Scale Image

### ISSUE THREAD

**Issue by chenguanqi** [sampepose/flownet2-tf#31]
Hi!
I wanna convert the result to Gray Scale Image whose number of channel is 1, rather than rgb which conains 3 channels. How can I do this?

**Comment by sampepose** [comment]
How would you encode optical flow into a single channel? The best you can do is two separate grayscale images (one in the x-direction, one in the y-direction).

The results get passed to `flow_to_image` here https://github.com/sampepose/flownet2-tf/blob/master/src/flowlib.py#L240. You can change that function to save two grayscale images instead of a single rgb image.

**Comment by zhangtongtong528** [comment]
Hi！
How to get the format of .flo optical flow file?

**Comment by Iamanorange** [comment]
In src/flowlib.py, `def write_flow(flow, filename)`.

**Comment by zhangtongtong528** [comment]
Thanks！I will try it now.

**Comment by zhangtongtong528** [comment]
Thank you very much

> In src/flowlib.py, `def write_flow(flow, filename)`.

Thank you very much!I got the .flo file.
And do you know how to get the optical image of my own datasets in batches?

**Comment by Iamanorange** [comment]
In the same file there is a `flow_to_image` function.

**Comment by zhangtongtong528** [comment]
> In the same file there is a `flow_to_image` function.
Sorry, what I want to ask is how to get the optical flow image from the original image in batches.

**Comment by Iamanorange** [comment]
You mean how to inference on multi-frames?

For example:
```python
with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, checkpoint)
    filename = os.listdir(framedir)[0]
    frame1 = np.asarray(Image.open(filename)) / 255
    re_list = List()
    for filename in os.listdir(framedir)[1:]:
        frame0 = frame1
        frame1 = np.asarray(Image.open(filename)) / 255
        pred_flow0 = sess.run(pred_flow, feed_dict={
            input_a : frame0,
            input_b : frame1
        })[0, :, :, :]
        re_list.append(pred_flow0)
    return re_list
```

**Comment by zhangtongtong528** [comment]
> You mean how to inference on multi-frames?
> 
> For example:
> 
> ```python
> with tf.Session() as sess:
>     saver = tf.train.Saver()
>     saver.restore(sess, checkpoint)
>     filename = os.listdir(framedir)[0]
>     frame1 = np.asarray(Image.open(filename)) / 255
>     re_list = List()
>     for filename in os.listdir(framedir)[1:]:
>         frame0 = frame1
>         frame1 = np.asarray(Image.open(filename)) / 255
>         pred_flow0 = sess.run(pred_flow, feed_dict={
>             input_a : frame0,
>             input_b : frame1
>         })[0, :, :, :]
>         re_list.append(pred_flow0)
>     return re_list
> ```
Sorry, please bother you again.Where should I add this code? And my images are in .jpg format. Do I need to convert it to other formats?

**Comment by zhangtongtong528** [comment]
and My question is how to get optical image from whole folder?

**Comment by Iamanorange** [comment]
Are you familiar with Python?

You don't need to convert image format since pillow or opencv was used as image loader. But it is better to use uncompressed(lossy) images. If you need compression, compress the optical flow then.

To get optical flow from whole folder, you can iterate frame pairs from the folder and calculate optical flow from each pair. You can refer to my code in the previous comment. There is no way to calculate video2video optical flow by FlowNet2.

**Comment by zhangtongtong528** [comment]
Thank you for your answer。Because I am just learning python,I will try the method you said.But the code for the iteration you said before is to add in which program file?  ./src/flownet2/test.py ?

**Comment by Iamanorange** [comment]
You can create a new python script as a caller. Or modify `test` function in src/net.py.
